# Getting started with numPy 

In [2]:
import numpy as np
nd_array = np.array([3, 33, 333]) # declare array
print(type(nd_array))

<class 'numpy.ndarray'>


In [5]:
print(nd_array.shape) # checking the shape of array

(3,)


In [6]:
print(nd_array[0], nd_array[1]) # access elements of array by index

3 33


In [7]:
nd_array[0] = 888 # ndarrays are mutable
print(nd_array)

[888  33 333]


### Creating 2D arrays

In [11]:
twod_array = np.array([[10,11,12], [14,15,16], [20,21,22]]) # two rank array
print(twod_array.shape)
print(twod_array)
print(twod_array[0,1])

(3, 3)
[[10 11 12]
 [14 15 16]
 [20 21 22]]
11


### Other ways to create arrays


In [16]:
import numpy as np

zeros = np.zeros((3,3)) # 3X3 array of zeros
print(zeros)

ones = np.ones((4,4)) # 4X4 array of zeros
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# filled with some value
all_nine = np.full((3,3), 9.0)
print(all_nine)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [20]:
# 3X3 matrix with diagonal 1 and other zero
eye = np.eye(3,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# create random array

rand = np.random.random((2,2))
print(rand)

[[0.98252842 0.26233027]
 [0.34208975 0.29637978]]


## Indexing Arrays


In [26]:
import numpy as np

an_array = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(an_array)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [28]:
# Slicing array to get 2X2 array from above
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [29]:
# Modifying slice will modify actual array
a_slice[0,0] = 44
print(an_array)

[[11 44 13]
 [21 22 23]
 [31 32 33]]


In [40]:
# Using both integer indexing & slicing generates and array of lower rank
rank1 = an_array[1, :]
print(rank1)
print(rank1.shape, an_array.shape)

[21 22 23]
(3,) (3, 3)


In [41]:
# slicing alone: makes the array of same rank as an_array
rank2 = an_array[1:2, :]
print(rank2)
print(rank2.shape, an_array.shape)

[[21 22 23]]
(1, 3) (3, 3)


In [43]:
# Can do same for colums

col_rank1 = an_array[:, 1]
print(col_rank1, col_rank1.shape)

col_rank2 = an_array[:, 1:2]
print(col_rank2, col_rank2.shape)

[44 22 32] (3,)
[[44]
 [22]
 [32]] (3, 1)
