# Getting started with numPy 

In [2]:
import numpy as np
nd_array = np.array([3, 33, 333]) # declare array
print(type(nd_array))

<class 'numpy.ndarray'>


In [5]:
print(nd_array.shape) # checking the shape of array

(3,)


In [6]:
print(nd_array[0], nd_array[1]) # access elements of array by index

3 33


In [7]:
nd_array[0] = 888 # ndarrays are mutable
print(nd_array)

[888  33 333]


### Creating 2D arrays

In [11]:
twod_array = np.array([[10,11,12], [14,15,16], [20,21,22]]) # two rank array
print(twod_array.shape)
print(twod_array)
print(twod_array[0,1])

(3, 3)
[[10 11 12]
 [14 15 16]
 [20 21 22]]
11


### Other ways to create arrays


In [16]:
import numpy as np

zeros = np.zeros((3,3)) # 3X3 array of zeros
print(zeros)

ones = np.ones((4,4)) # 4X4 array of zeros
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# filled with some value
all_nine = np.full((3,3), 9.0)
print(all_nine)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [20]:
# 3X3 matrix with diagonal 1 and other zero
eye = np.eye(3,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# create random array

rand = np.random.random((2,2))
print(rand)

[[0.98252842 0.26233027]
 [0.34208975 0.29637978]]


## Indexing Arrays


In [26]:
import numpy as np

an_array = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(an_array)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [28]:
# Slicing array to get 2X2 array from above
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [29]:
# Modifying slice will modify actual array
a_slice[0,0] = 44
print(an_array)

[[11 44 13]
 [21 22 23]
 [31 32 33]]


In [40]:
# Using both integer indexing & slicing generates and array of lower rank
rank1 = an_array[1, :]
print(rank1)
print(rank1.shape, an_array.shape)

[21 22 23]
(3,) (3, 3)


In [41]:
# slicing alone: makes the array of same rank as an_array
rank2 = an_array[1:2, :]
print(rank2)
print(rank2.shape, an_array.shape)

[[21 22 23]]
(1, 3) (3, 3)


In [43]:
# Can do same for colums

col_rank1 = an_array[:, 1]
print(col_rank1, col_rank1.shape)

col_rank2 = an_array[:, 1:2]
print(col_rank2, col_rank2.shape)

[44 22 32] (3,)
[[44]
 [22]
 [32]] (3, 1)


## Boolean Indexing 

In [3]:
import numpy as np
#Create an array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33]])

# Create a filter which will be boolean value if element in array is greater than 15
filter =(an_array > 15)

filter

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# Select those value using filter
print(an_array[filter])

[21 22 23 31 32 33]


In [6]:
# all it in one step
an_array[an_array>15]

array([21, 22, 23, 31, 32, 33])

In [7]:
# can use logical expression with filters
an_array[(an_array>15) & (an_array<25)]

array([21, 22, 23])

In [10]:
#Change elements of an array using filter
an_array[(an_array>15) & (an_array<25)] +=100
print(an_array)

[[ 11  12  13]
 [121 122 123]
 [ 31  32  33]]


## Data Types and Operations

In [14]:
#Python automatically assigns the datatype
ex1 = np.array([20,21])
print(ex1.dtype)

int64


In [20]:
#Assign your data type: 'Python will force data type and change value accordingly'
# Generally the result will be upcast
ex2 = np.array([10.2,11.4], dtype=np.int64)
print(ex2.dtype)
print(ex2)

int64
[10 11]


In [25]:
#add
x = np.array([20,21])
y = np.array([10.0,11.5], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[30.  32.5]
[30.  32.5]


In [32]:
#subtract
print(x - y)
print(np.subtract(x,y))

[10.   9.5]
[10.   9.5]


In [34]:
# multiply
print(x * y)
print(np.multiply(x,y))

[200.  241.5]
[200.  241.5]


In [37]:
# Divide 
print(x / y)
print(np.divide(x,y))

[2.         1.82608696]
[2.         1.82608696]


In [39]:
#Sqrt
print(np.sqrt(y))

[3.16227766 3.39116499]


## Statistic,Sorting and Set Operations


<h3 style="color:blue;">Stats Basics</h3>

In [42]:
# get 2X4 random array
arr = 10 * np.random.randn(2,4)
print(arr)

[[  2.02461414   6.32963816  11.03194776   7.13064182]
 [-15.75216386 -11.78683542   0.55047421   7.96873253]]


In [44]:
#Compute the mean for all elements
print(arr.mean())

0.9371311691486586


In [45]:
#Compute the mean for 'row' :  1 for row
print(arr.mean(axis =1))

[ 6.62921047 -4.75494813]


In [46]:
#Compute the mean for 'column' : 0 for colums
print(arr.mean(axis = 0))

[-6.86377486 -2.72859863  5.79121099  7.54968718]


In [47]:
#Sum all elements
print(arr.sum())

7.497049353189269


In [48]:
#Compute the meadian for 'row' 
print(np.median(arr, axis =1))

[ 6.73013999 -5.6181806 ]


In [49]:
#Compute the meadian for 'colums' 
print(np.median(arr, axis =0))

[-6.86377486 -2.72859863  5.79121099  7.54968718]


<h3 style="color:blue;"> Sorting </h3>

In [52]:
# Create unsorted array of 10 elements
us = np.random.randn(10)
print(us)

[-0.93618741  0.14404782  1.40853178  0.12744507  0.26566051 -0.20989961
 -0.12321604  1.04228529  0.43656876  0.12562071]


In [53]:
#Create copy and Sort
sorted = np.array(us)
sorted.sort()
print(sorted)
print(us)

[-0.93618741 -0.20989961 -0.12321604  0.12562071  0.12744507  0.14404782
  0.26566051  0.43656876  1.04228529  1.40853178]
[-0.93618741  0.14404782  1.40853178  0.12744507  0.26566051 -0.20989961
 -0.12321604  1.04228529  0.43656876  0.12562071]


In [55]:
#finding unique elemets in the array
array = np.array([1,2,4,2,6,5,6])
print(np.unique(array))

[1 2 4 5 6]


<h3 style="color:blue;"> Set Operations </h3>

In [57]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])

print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [58]:
# intersect 1D array
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [59]:
# union 1D array
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [60]:
print(np.setdiff1d(s1, s2)) # element in s1 not in s2

['desk']


In [61]:
print(np.in1d(s1, s2)) # element in s1 also in s2

[False  True  True]


## Broadcasting

In [63]:
#Create array 4X3 of zeros
z_arr = np.zeros((4,3))
print(z_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [65]:
#Create one rank array
add_arr = np.array([1,0,2])
print(add_arr)

[1 0 2]


In [67]:
#Add each colum or 'z_arr' using broadcasting
y = z_arr + add_arr
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]
